name: festim-benchmark-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.9.0
  - matplotlib
  - pandas
  - python-gmsh
  - meshio
  - scifem=0.2.8
  - ipykernel
  - ipyparallel
  - nbconvert
  - pip
  - pip:
      - git+https://github.com/remdelaportemathurin/festim@change-of-var-method
