name: festim-benchmark-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.9.0
  - matplotlib
  - pandas
  - python-gmsh
  - meshio
  - scifem
  - ipykernel
  - ipyparallel
  - pip:
      - git+https://github.com/remdelaportemathurin/festim@discontinuity-generic
